[project]
name = 'Oncall-Adrenaline-Converter'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.am3-metric-psychic]
path = 'contracts/am3-metric-psychic.clar'
clarity_version = 3
epoch = 'latest'

[contracts.postmortem-lorem-ipsum]
path = 'contracts/postmortem-lorem-ipsum.clar'
clarity_version = 3
epoch = '3.2'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
